export type OrderStatus = "Pending" | "Ready for Pickup" | "Complete";
export type OrderType = "regular" | "custom";

export interface DashboardOrder {
  id: string;
  name: string;      
  order: string;     
  date: string;      
  due: string;       
  status: OrderStatus;
  type: OrderType;    
  productId: string; 
  totalPaid: number;  
}
const Orders: DashboardOrder[] = [
  {
    id: "ORD-1001",
    name: "Emily Johnson",
    order: '6" Celebration Cake – Vanilla + Strawberry',
    date: "2025-11-20",
    due: "2025-11-27",
    status: "Pending",
    type: "regular",
    productId: "CAKE_6_REGULAR",
    totalPaid: 65,
  },
  {
    id: "ORD-1002",
    name: "Michael Chen",
    order: "Dozen Assorted Cupcakes",
    date: "2025-11-19",
    due: "2025-11-26",
    status: "Ready for Pickup",
    type: "regular",
    productId: "CUPCAKES_DOZEN",
    totalPaid: 42,
  },
  {
    id: "ORD-1003",
    name: "Sofia Martinez",
    order: '9" Chocolate Fudge Birthday Cake',
    date: "2025-11-18",
    due: "2025-11-25",
    status: "Pending",
    type: "regular",
    productId: "CAKE_9_CHOC_FUDGE",
    totalPaid: 75,
  },
  {
    id: "ORD-1004",
    name: "David Lee",
    order: "Half Sheet Cake – Funfetti",
    date: "2025-11-15",
    due: "2025-11-22",
    status: "Complete",
    type: "regular",
    productId: "SHEET_HALF_FUNFETTI",
    totalPaid: 110,
  },
  {
    id: "ORD-1005",
    name: "Ava Thompson",
    order: "Gluten-Free Cupcake Box (12)",
    date: "2025-11-16",
    due: "2025-11-23",
    status: "Ready for Pickup",
    type: "regular",
    productId: "CUPCAKES_GF_DOZEN",
    totalPaid: 48,
  },
  {
    id: "ORD-1006",
    name: "Noah Williams",
    order: '6" Red Velvet Cake',
    date: "2025-11-21",
    due: "2025-11-28",
    status: "Pending",
    type: "regular",
    productId: "CAKE_6_RED_VELVET",
    totalPaid: 60,
  },
  {
    id: "ORD-1007",
    name: "Olivia Brown",
    order: "Cookie Platter – 3 Dozen",
    date: "2025-11-14",
    due: "2025-11-21",
    status: "Complete",
    type: "regular",
    productId: "COOKIES_PLATTER_3DOZEN",
    totalPaid: 54,
  },
  {
    id: "ORD-1008",
    name: "Liam Davis",
    order: "Custom Cake – Soccer Theme",
    date: "2025-11-17",
    due: "2025-11-24",
    status: "Pending",
    type: "custom",
    productId: "CAKE_CUSTOM_SOCCER",
    totalPaid: 135,
  },
  {
    id: "ORD-1009",
    name: "Grace Miller",
    order: "Custom Cake – Baby Shower, Lemon + Raspberry",
    date: "2025-11-13",
    due: "2025-11-20",
    status: "Pending",
    type: "custom",
    productId: "CAKE_CUSTOM_BABY_SHOWER",
    totalPaid: 150,
  },
  {
    id: "ORD-1010",
    name: "Ethan Clark",
    order: "Dozen Chocolate Chip Cookies",
    date: "2025-11-12",
    due: "2025-11-19",
    status: "Ready for Pickup",
    type: "regular",
    productId: "COOKIES_DOZEN_CHOC_CHIP",
    totalPaid: 24,
  },
  {
    id: "ORD-1011",
    name: "Isabella Garcia",
    order: "Custom Cupcake Tower – Pastel Theme (36)",
    date: "2025-11-11",
    due: "2025-11-23",
    status: "Pending",
    type: "custom",
    productId: "CUPCAKE_TOWER_PASTEL",
    totalPaid: 160,
  },
  {
    id: "ORD-1012",
    name: "James Anderson",
    order: "Flan Tray – 12 Servings",
    date: "2025-11-10",
    due: "2025-11-17",
    status: "Complete",
    type: "regular",
    productId: "FLAN_TRAY_12",
    totalPaid: 45,
  },
  {
    id: "ORD-1013",
    name: "Mia Robinson",
    order: "2 Dozen Cuban Pastelitos – Guava & Cheese",
    date: "2025-11-09",
    due: "2025-11-16",
    status: "Ready for Pickup",
    type: "regular",
    productId: "PASTELITOS_2DOZEN",
    totalPaid: 60,
  },
  {
    id: "ORD-1014",
    name: "Benjamin White",
    order: '8" Carrot Cake – Cream Cheese Frosting',
    date: "2025-11-08",
    due: "2025-11-15",
    status: "Complete",
    type: "regular",
    productId: "CAKE_8_CARROT",
    totalPaid: 70,
  },
  {
    id: "ORD-1015",
    name: "Charlotte Harris",
    order: "Custom Wedding Cake – 3 Tier, White + Gold",
    date: "2025-11-07",
    due: "2025-11-30",
    status: "Pending",
    type: "custom",
    productId: "CAKE_CUSTOM_WEDDING_3TIER",
    totalPaid: 520,
  },
  {
    id: "ORD-1016",
    name: "Daniel Young",
    order: "Dozen Red Velvet Cupcakes",
    date: "2025-11-06",
    due: "2025-11-13",
    status: "Ready for Pickup",
    type: "regular",
    productId: "CUPCAKES_DOZEN_RED_VELVET",
    totalPaid: 44,
  },
  {
    id: "ORD-1017",
    name: "Amelia King",
    order: '6" Vanilla Cake – Rainbow Sprinkles',
    date: "2025-11-05",
    due: "2025-11-12",
    status: "Complete",
    type: "regular",
    productId: "CAKE_6_VANILLA_RAINBOW",
    totalPaid: 55,
  },
  {
    id: "ORD-1018",
    name: "Logan Scott",
    order: "Custom Sheet Cake – Corporate Logo",
    date: "2025-11-04",
    due: "2025-11-18",
    status: "Pending",
    type: "custom",
    productId: "CAKE_CUSTOM_CORP_LOGO",
    totalPaid: 230,
  },
  {
    id: "ORD-1019",
    name: "Harper Green",
    order: "Cookie Platter – Assorted",
    date: "2025-11-03",
    due: "2025-11-10",
    status: "Ready for Pickup",
    type: "regular",
    productId: "COOKIES_PLATTER_ASSORTED",
    totalPaid: 48,
  },
  {
    id: "ORD-1020",
    name: "Jacob Baker",
    order: '9" Lemon Blueberry Cake',
    date: "2025-11-02",
    due: "2025-11-09",
    status: "Complete",
    type: "regular",
    productId: "CAKE_9_LEMON_BLUEBERRY",
    totalPaid: 72,
  },
  {
    id: "ORD-1021",
    name: "Emma Rodriguez",
    order: "Custom Cake – Encanto Theme",
    date: "2025-11-01",
    due: "2025-11-14",
    status: "Pending",
    type: "custom",
    productId: "CAKE_CUSTOM_ENCANTO",
    totalPaid: 180,
  },
  {
    id: "ORD-1022",
    name: "William Turner",
    order: "Dozen Vanilla Cupcakes – Pink Buttercream",
    date: "2025-10-31",
    due: "2025-11-07",
    status: "Ready for Pickup",
    type: "regular",
    productId: "CUPCAKES_DOZEN_VANILLA_PINK",
    totalPaid: 40,
  },
  {
    id: "ORD-1023",
    name: "Evelyn Collins",
    order: "Flan – Individual Cups (10)",
    date: "2025-10-30",
    due: "2025-11-06",
    status: "Complete",
    type: "regular",
    productId: "FLAN_CUPS_10",
    totalPaid: 38,
  },
  {
    id: "ORD-1024",
    name: "Alexander Perez",
    order: "Custom Cake – Gaming Controller Design",
    date: "2025-10-29",
    due: "2025-11-10",
    status: "Pending",
    type: "custom",
    productId: "CAKE_CUSTOM_GAMING",
    totalPaid: 165,
  },
  {
    id: "ORD-1025",
    name: "Avery Brooks",
    order: "Half Sheet Cake – Chocolate + Cookies & Cream",
    date: "2025-10-28",
    due: "2025-11-04",
    status: "Ready for Pickup",
    type: "regular",
    productId: "SHEET_HALF_CHOC_OREO",
    totalPaid: 120,
  },
  {
    id: "ORD-1026",
    name: "Henry Foster",
    order: "Cookie Platter – Holiday Assortment",
    date: "2025-10-27",
    due: "2025-11-03",
    status: "Pending",
    type: "regular",
    productId: "COOKIES_PLATTER_HOLIDAY",
    totalPaid: 52,
  },
  {
    id: "ORD-1027",
    name: "Scarlett Morgan",
    order: "Custom Cupcakes – Unicorn Theme (24)",
    date: "2025-10-26",
    due: "2025-11-05",
    status: "Pending",
    type: "custom",
    productId: "CUPCAKES_24_UNICORN",
    totalPaid: 96,
  },
  {
    id: "ORD-1028",
    name: "Jack Rivera",
    order: '6" Marble Cake – Chocolate Ganache',
    date: "2025-10-25",
    due: "2025-11-01",
    status: "Complete",
    type: "regular",
    productId: "CAKE_6_MARBLE_GANACHE",
    totalPaid: 62,
  },
  {
    id: "ORD-1029",
    name: "Luna Reed",
    order: "Dozen Pastelitos – Mixed Flavors",
    date: "2025-10-24",
    due: "2025-10-31",
    status: "Ready for Pickup",
    type: "regular",
    productId: "PASTELITOS_MIXED_1DOZEN",
    totalPaid: 30,
  },
  {
    id: "ORD-1030",
    name: "Matthew Cox",
    order: "Custom Cake – Retirement Party, Golf Theme",
    date: "2025-10-23",
    due: "2025-11-06",
    status: "Pending",
    type: "custom",
    productId: "CAKE_CUSTOM_RETIREMENT_GOLF",
    totalPaid: 190,
  },
  {
    id: "ORD-1031",
    name: "Zoey Ward",
    order: '8" Strawberry Shortcake',
    date: "2025-11-29",
    due: "2025-12-01", // today-ish
    status: "Ready for Pickup",
    type: "regular",
    productId: "CAKE_8_STRAWBERRY_SHORTCAKE",
    totalPaid: 72,
  },
  {
    id: "ORD-1032",
    name: "Ryan Murphy",
    order: "Dozen Cookies – Peanut Butter & Chocolate",
    date: "2025-11-30",
    due: "2025-12-02", // tomorrow-ish
    status: "Pending",
    type: "regular",
    productId: "COOKIES_DOZEN_PB_CHOC",
    totalPaid: 26,
  },
  {
    id: "ORD-1033",
    name: "Penelope Hughes",
    order: "Custom Cake – Princess Castle",
    date: "2025-11-30",
    due: "2025-12-05",
    status: "Pending",
    type: "custom",
    productId: "CAKE_CUSTOM_PRINCESS",
    totalPaid: 210,
  },
  {
    id: "ORD-1034",
    name: "Mason Bell",
    order: "Flan Tray – Caramel",
    date: "2025-11-27",
    due: "2025-12-10",
    status: "Pending",
    type: "regular",
    productId: "FLAN_TRAY_CARAMEL",
    totalPaid: 48,
  },
  {
    id: "ORD-1035",
    name: "Chloe Adams",
    order: "Custom Cupcakes – Baby Gender Reveal (24)",
    date: "2025-11-25",
    due: "2025-12-15",
    status: "Pending",
    type: "custom",
    productId: "CUPCAKES_24_GENDER_REVEAL",
    totalPaid: 98,
  },
  {
    id: "ORD-1036",
    name: "Nathan Cooper",
    order: "Half Sheet Cake – Vanilla + Fresh Berries",
    date: "2025-12-01",
    due: "2025-12-24",
    status: "Pending",
    type: "regular",
    productId: "SHEET_HALF_VANILLA_BERRIES",
    totalPaid: 125,
  },
  {
    id: "ORD-1037",
    name: "Layla Mitchell",
    order: "Dozen Red Velvet Cupcakes – Cream Cheese Frosting",
    date: "2025-12-02",
    due: "2025-12-31",
    status: "Pending",
    type: "regular",
    productId: "CUPCAKES_DOZEN_REDVELVET_CC",
    totalPaid: 46,
  },
  {
    id: "ORD-1038",
    name: "Isaac Torres",
    order: "Custom Cake – Baseball Team Logo",
    date: "2025-12-05",
    due: "2026-01-05",
    status: "Pending",
    type: "custom",
    productId: "CAKE_CUSTOM_BASEBALL",
    totalPaid: 175,
  },
  {
    id: "ORD-1039",
    name: "Nora Price",
    order: "Cookie Platter – Kids Birthday Assortment",
    date: "2025-12-07",
    due: "2026-01-10",
    status: "Pending",
    type: "regular",
    productId: "COOKIES_PLATTER_KIDS",
    totalPaid: 50,
  },
  {
    id: "ORD-1040",
    name: "Sebastian Flores",
    order: "Custom Wedding Dessert Table – Mixed Items",
    date: "2025-12-10",
    due: "2026-01-20",
    status: "Pending",
    type: "custom",
    productId: "DESSERT_TABLE_WEDDING",
    totalPaid: 680,
  },
];

export default Orders;